### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Skinexxl** [RitaSister/DonateCase#1]
### Server Implementation

Paper

### Server Version

1.17.2

### Describe the bug

[21:42:18 WARN]: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure
[21:42:18 WARN]:
[21:42:18 WARN]: The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
[21:42:18 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174)
[21:42:18 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
[21:42:18 WARN]:        at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:833)
[21:42:18 WARN]:        at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:453)
[21:42:18 WARN]:        at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246)
[21:42:18 WARN]:        at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
[21:42:18 WARN]:        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
[21:42:18 WARN]:        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
[21:42:18 WARN]:        at DonateCase-0.1.6.jar//net.ritasister.dc.MySQL.<init>(MySQL.java:21)
[21:42:18 WARN]:        at DonateCase-0.1.6.jar//net.ritasister.dc.DonateCase$1.run(DonateCase.java:93)
[21:42:18 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
[21:42:18 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[21:42:18 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1135)
[21:42:18 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[21:42:18 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[21:42:18 WARN]: Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure
[21:42:18 WARN]:
[21:42:18 WARN]: The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
[21:42:18 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[21:42:18 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78)
[21:42:18 WARN]:        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[21:42:18 WARN]:        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[21:42:18 WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[21:42:18 WARN]:        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
[21:42:18 WARN]:        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
[21:42:18 WARN]:        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
[21:42:18 WARN]:        at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
[21:42:18 WARN]:        at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:89)
[21:42:18 WARN]:        at com.mysql.cj.NativeSession.connect(NativeSession.java:144)
[21:42:18 WARN]:        at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:953)
[21:42:18 WARN]:        at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:823)
[21:42:18 WARN]:        ... 12 more
[21:42:18 WARN]: Caused by: java.net.ConnectException: Connection refused: connect
[21:42:18 WARN]:        at java.base/sun.nio.ch.Net.connect0(Native Method)
[21:42:18 WARN]:        at java.base/sun.nio.ch.Net.connect(Net.java:576)
[21:42:18 WARN]:        at java.base/sun.nio.ch.Net.connect(Net.java:565)
[21:42:18 WARN]:        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
[21:42:18 WARN]:        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333)
[21:42:18 WARN]:        at java.base/java.net.Socket.connect(Socket.java:645)
[21:42:18 WARN]:        at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:155)
[21:42:18 WARN]:        at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:63)
[21:42:18 WARN]:        ... 15 more
[21:42:18 INFO]: [DonateCase] Disabling DonateCase v0.1.6
[21:42:18 WARN]: [DonateCase] Task #531 for DonateCase v0.1.6 generated an exception
java.lang.NullPointerException: Cannot invoke "java.sql.Statement.executeQuery(String)" because "this.stmt" is null
        at net.ritasister.dc.MySQL.hasTable(MySQL.java:70) ~[DonateCase-0.1.6.jar:?]
        at net.ritasister.dc.DonateCase$1.run(DonateCase.java:94) ~[DonateCase-0.1.6.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-165]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Paper-165]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1135) ~[patched_1.17.1.jar:git-Paper-165]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-165]
        at java.lang.Thread.run(Thread.java:831) [?:?]

### To Reproduce

see error

### Expected behaviour

work

### DonateCase version

0.1.6

### Checklist

- [x] I am using the newest build from https://github.com/RitaSister/ServerRegionProtect/releases/ and the issue still persists.

**Comment by RitaSister** [comment]
Это не ошибка уже плагина. У вас закрывается соединение с базой данных быстрее чем может узнать об этом плагин и по этому эта ошибка вылезает. Проверьте на вашей стороне настройки таймаута в базе данных.
