### ISSUE TITLE
eror

### ISSUE THREAD

**Issue by Skinexxl** [RitaSister/DonateCase#2]
### Server Implementation

Paper

### Server Version

1.17.2

### Describe the bug

[19:04:15 WARN]: java.sql.SQLException: No suitable driver found for s59.craft-hosting.ru
[19:04:15 WARN]: at java.sql/java.sql.DriverManager.getConnection(Unknown Source)
[19:04:15 WARN]: at java.sql/java.sql.DriverManager.getConnection(Unknown Source)
[19:04:15 WARN]: at DonateCase-0.1.6 (1).jar//net.ritasister.dc.MySQL.init(MySQL.java:21)
[19:04:15 WARN]: at DonateCase-0.1.6 (1).jar//net.ritasister.dc.DonateCase$1.run(DonateCase.java:93)
[19:04:15 WARN]: at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
[19:04:15 WARN]: at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[19:04:15 WARN]: at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1221)
[19:04:15 WARN]: at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[19:04:15 WARN]: at java.base/java.lang.Thread.run(Unknown Source)

### To Reproduce

see eror

### Expected behaviour

1

### DonateCase version

0.1.6

### Checklist

- [X] I am using the newest build from https://github.com/RitaSister/ServerRegionProtect/releases/ and the issue still persists.

**Comment by RitaSister** [comment]
Какой указываете драйвер?
